language: cpp

compiler:
 - clang
 - gcc

env:
 - config=debug64   config_suffix=debug_x64_gmake
 - config=release64 config_suffix=release_x64_gmake

before_install:
  - sudo add-apt-repository -y ppa:codegear/release
  - sudo apt-get update -qq
  - sudo apt-get install -y premake4 valgrind

install: true

before_script:
  - cd build 
  - premake4 'gmake'
  - cd "${TRAVIS_BUILD_DIR}"

script:
#  - make -C build/gmake -f test.make
#  - make -C build/gmake -f example.make 
   - cd bin
#  - ./unittest_${config_suffix}
#  - valgrind --leak-check=full --error-exitcode=1 ./unittest_${config_suffix}
#  - ./perftest_${config_suffix}

after_success:
  - if [ "$config" = "release64" -a "$CC" = "clang" ]; then cd /tmp; fi
  - if [ "$config" = "release64" -a "$CC" = "clang" ]; then git clone https://github.com/doxygen/doxygen.git; fi
  - if [ "$config" = "release64" -a "$CC" = "clang" ]; then cd doxygen; fi
  - if [ "$config" = "release64" -a "$CC" = "clang" ]; then ./configure; fi
  - if [ "$config" = "release64" -a "$CC" = "clang" ]; then make; fi
  - if [ "$config" = "release64" -a "$CC" = "clang" ]; then make distclean; fi
  - if [ "$config" = "release64" -a "$CC" = "clang" ]; then git pull; fi
  - if [ "$config" = "release64" -a "$CC" = "clang" ]; then ./configure; fi
  - if [ "$config" = "release64" -a "$CC" = "clang" ]; then make; fi
  - if [ "$config" = "release64" -a "$CC" = "clang" ]; then sudo make install; fi
  - if [ "$config" = "release64" -a "$CC" = "clang" ]; then cd "${TRAVIS_BUILD_DIR}"; fi
  - if [ "$config" = "release64" -a "$CC" = "clang" ]; then doxygen build/Doxyfile; fi
