language: generic
services:
  - docker

env:
  global:
    - DOCKER_RUN_OPTS="-e EMSDK -e EM_CONFIG=/root/.emscripten -e EM_CACHE -e EMSDK_NODE -v ${TRAVIS_BUILD_DIR}/.emsdk:${TRAVIS_BUILD_DIR}/.emsdk -v ${HOME}/.emscripten:/root/.emscripten"
  matrix:
    - ROS_DISTRO="melodic" ROS_REPO="main"
    - ROS_DISTRO="melodic" ROS_REPO="testing"

install:
  - git clone https://github.com/emscripten-core/emsdk.git .emsdk
  - cd .emsdk
  - ./emsdk install latest
  - ./emsdk activate latest
  - cd ..
  - git clone --quiet --depth 1 https://github.com/ros-industrial/industrial_ci.git .industrial_ci -b master
  - source .emsdk/emsdk_env.sh

script:
  - .industrial_ci/travis.sh
