language: cpp

compiler:
 - clang
 - gcc

env:
  matrix:
    - config=debug64   config_suffix=debug_x64_gmake
    - config=release64 config_suffix=release_x64_gmake
  global:
    secure: "PoHpnUX6AnuS0Rj2lytxG63cgU8r8dph4z2eSlc0q401nzakOgRRdhzuIqFyAv+qfihUoWi/xwCzAI8d67qamBFR6YUCsdQ5wpFZ3kHg4ZhlIlvAxOWcCcpWwwSqlQboGbv/JAWdnBaCXzyuA6soKyY32LSgMaUP2kOcwhbZvxo="

before_install:
  - sudo add-apt-repository -y ppa:codegear/release
  - sudo apt-get update -qq
  - sudo apt-get install -y premake4 valgrind

install: true

before_script:
  - pushd build && premake4 'gmake' && popd

script:
  - make -C build/gmake -f test.make
  - make -C build/gmake -f example.make
  - pushd bin
  - ./unittest_${config_suffix}
  - valgrind --leak-check=full --error-exitcode=1 ./unittest_${config_suffix}
  - if [ "$config" = "release64" ]; then ./perftest_${config_suffix}; fi
  - popd
  - ./build/travis-doxygen.sh;
