name: CI

on: [push, pull_request]

jobs:
  industrial_ci:
    strategy:
      matrix:
        env:
          - {ROS_DISTRO: melodic, ROS_REPO: testing}
          - {ROS_DISTRO: melodic, ROS_REPO: main}
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      #- uses: mymindstorm/setup-emsdk@v4
      - uses: lovasoa/setup-emscripten@master
        with:
          emscripten-version: '1.39.10'
      - uses: 'ros-industrial/industrial_ci@master'
        env: ${{matrix.env}}
